"""
pipeline/dispatch.py — the weekly dispatch (ARCHITECTURE-PHASE2-4.md §11, day 9).

Binding rules exercised here:

  - Class A only. Every figure in the message is a count or a rate that came
    out of `pipeline/stats.py` over a window `stats.window` selected. The
    dispatch composes and formats; it never derives a statistic
    (ARCHITECTURE-PHASE2-4.md §0).
  - Never a number without its denominator (CONSTRAINTS.md #3): every line
    that prints a percentage prints the counts it came from.
  - Never fake precision (CONSTRAINTS.md #4): below n = 30 a figure renders
    "not enough data (n=…)", and the insight line — which is a fact, not a
    filler — is omitted rather than invented.
  - No sentence tells the reader what to do with a number (CONSTRAINTS.md
    NOT-THIS list), enforced here by the banned-word check over the whole
    rendered message, both renderings.

The fixture is frozen (`pipeline/tests/fixtures/dispatch/`, generated by
`make_dispatch_fixture.py`), so an hourly crawl can never move a test.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from pipeline import dispatch

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "dispatch"


# --- the banned-word check --------------------------------------------------
# The list is the brief's, and it is applied with word boundaries for the
# word-shaped terms for the same reason scripts/lint-copy.sh does: a bare
# substring test for "edge" matches "ledge.tools", which the footer is
# required to carry, and a bare "ape" matches "shape". `probab` and `predict`
# are prefix-matched so "probability"/"probabilities"/"predicted" are caught.
# `will ` stays a literal: it is the future tense the copy must never take.
BANNED_PATTERNS = [
    r"\bscore\b", r"\bscores\b", r"\bscoring\b",
    r"\brisk\b", r"\brisks\b", r"\brisky\b",
    r"\bodds\b",
    r"\bchance\b", r"\bchances\b",
    r"\blikely\b",
    r"\bsafe\b", r"\bsafer\b", r"\bsafety\b",
    r"\brug\b", r"\brugs\b",
    r"\bprobab",
    r"\bpredict",
    r"will ",
    r"\bshould\b",
    r"\bbuy\b", r"\bbuys\b", r"\bbuying\b",
    r"\bsell\b", r"\bsells\b", r"\bselling\b",
    r"\bape\b", r"\bapes\b", r"\baping\b",
    r"\balpha\b",
    r"\bedge\b",
    r"\bsignals\b",
]
BANNED_RE = re.compile("|".join(BANNED_PATTERNS), re.IGNORECASE)


@pytest.fixture(scope="module")
def composed():
    return dispatch.compose(*dispatch.load_inputs(FIXTURE_DIR))


@pytest.fixture(scope="module")
def plain(composed):
    return dispatch.render_text(composed)


@pytest.fixture(scope="module")
def html(composed):
    return dispatch.render_html(composed)


# --- composition from the frozen fixture ------------------------------------
def test_window_is_the_trailing_seven_days_of_the_measurement(composed):
    assert composed["windowDays"] == 7
    assert composed["until"] - composed["since"] == 7 * 86400
    assert composed["crawledAt"] == "2026-09-06T00:00:00Z"


def test_the_window_excludes_launches_before_it(composed):
    """The fixture holds 1,440 launches and 1,400 of them are in the window;
    the denominator is the window's, not the file's."""
    assert composed["d7"]["launches"] == 1400


def test_the_number_line_is_counts_then_the_rate(plain):
    assert "Pons, last 7 days: 76 of 1,400 launches graduated, 5.43%." in plain


def test_the_excluding_fast_line_carries_its_one_in_n(plain):
    assert (
        "Excluding launches that graduated inside 5 min: 27 of 1,400, 1.93% (1 in 52)."
        in plain
    )


def test_the_pair_cohort_line_names_the_two_furthest_apart_with_counts(plain):
    assert (
        "Pair token, furthest apart: Stablecoin 41 of 350 graduated, 11.7%; "
        "Other 7 of 350, 2.0%." in plain
    )


def test_the_tax_cohort_line_names_the_two_furthest_apart_with_counts(plain):
    assert (
        "Creator tax, furthest apart: 0% 25 of 280 graduated, 8.9%; "
        "6–10% 7 of 280, 2.5%." in plain
    )


def test_the_cohort_lines_state_counts_and_disclaim_a_cause(plain):
    assert plain.count("Two counts over the same 7 days, not a cause.") == 2


def test_the_time_to_graduation_line_carries_p50_p90_and_its_n(plain):
    assert (
        "Time to graduation, over 76 graduations measured: "
        "half within 2 min, 9 in 10 within 1 h 8 min." in plain
    )


def test_the_insight_line_is_a_fact_from_the_ladder_with_its_n(plain):
    assert "Graduations that completed in under 60 s: 23 of 76 measured (30.3%)." in plain


def test_the_blocks_are_in_the_briefed_order(composed):
    assert [b["id"] for b in composed["blocks"]] == [
        "number",
        "cohorts",
        "ttg",
        "insight",
    ]


def test_the_footer_carries_the_measurement_time_site_method_and_unsubscribe(plain):
    assert "Measured 6 Sep 2026 · 00:00 UTC" in plain
    assert "ledge.tools" in plain
    assert "https://ledge.tools/method" in plain
    assert "{{{RESEND_UNSUBSCRIBE_URL}}}" in plain


def test_the_subject_leads_with_the_excluding_fast_figure(composed):
    assert composed["subject"] == "LEDGE — 7 days: 1 in 52, excluding graduations inside 5 min"


# --- CONSTRAINTS -------------------------------------------------------------
def test_no_banned_word_in_either_rendering(plain, html):
    for name, message in (("text", plain), ("html", html)):
        found = BANNED_RE.findall(message)
        assert found == [], f"{name} rendering holds banned copy: {found}"


def test_the_banned_word_check_can_fail():
    """The guard above is only worth having if it fires. If this ever passes
    an empty list the check above is asserting nothing."""
    assert BANNED_RE.findall("this token is likely safe, you should buy")


def test_every_figure_carries_its_denominator(plain):
    """CONSTRAINTS.md #3. Every line that prints a percentage prints either
    the counts it was computed from or the n it was suppressed for."""
    for line in plain.splitlines():
        if "%" not in line:
            continue
        assert " of " in line or "n=" in line, f"percentage without its n: {line}"


def test_no_address_appears_in_the_message(plain, html):
    """CONSTRAINTS.md #2: no wallet or token address is ever a subject."""
    for message in (plain, html):
        assert re.search(r"0x[0-9a-fA-F]{40}", message) is None


def test_the_html_rendering_says_the_same_sentences_as_the_plain_one(composed, plain, html):
    for block in composed["blocks"]:
        for line in block["lines"]:
            assert line in plain
            assert dispatch.escape_html(line) in html


def test_the_html_is_the_design_idiom_and_holds_no_image(html):
    assert "#EFEAE0" in html  # --ground, the bone sheet
    assert "#16130F" in html  # --ink
    assert "border-radius" not in html
    assert "box-shadow" not in html
    assert "<img" not in html


# --- the insufficient window -------------------------------------------------
@pytest.fixture(scope="module")
def thin():
    """A window holding fewer launches than the gate allows, composed the
    same way. Twelve launches, three graduations: nothing may be printed as
    a percentage and the insight has no fact to state."""
    number, launches, graduations = dispatch.load_inputs(FIXTURE_DIR)
    until = dispatch.parse_iso(number["crawledAt"])
    kept = [l for l in launches if l["ts"] >= until - 7 * 86400][:12]
    tokens = {l["token"] for l in kept}
    kept_grads = [g for g in graduations if g["token"] in tokens][:3]
    return dispatch.compose(number, kept, kept_grads)


def test_a_thin_window_renders_not_enough_data_rather_than_a_rate(thin):
    text = dispatch.render_text(thin)
    assert "not enough data (n=12)" in text
    assert "%" not in text


def test_a_thin_window_omits_the_insight_rather_than_inventing_one(thin):
    assert [b["id"] for b in thin["blocks"]] == ["number", "cohorts", "ttg"]
    assert "insight" not in [b["id"] for b in thin["blocks"]]
    assert "completed in under" not in dispatch.render_text(thin)


def test_a_thin_window_still_carries_every_denominator(thin):
    text = dispatch.render_text(thin)
    # The counts are still printed — they are observations, and suppressing
    # them would hide the sample rather than the rate. Only the rate goes.
    assert "Pons, last 7 days: 2 of 12 launches graduated, not enough data (n=12)." in text
    assert "Excluding launches that graduated inside 5 min: 1 of 12, not enough data (n=12)." in text
    assert "Pair token: not enough data (n=12)." in text
    assert "Creator tax: not enough data (n=12)." in text
    assert "Time to graduation: not enough data (n=2)." in text


def test_a_thin_window_subject_names_the_sample_not_a_figure(thin):
    assert thin["subject"] == "LEDGE — 7 days: not enough data (n=12)"


def test_a_thin_window_passes_the_banned_word_check(thin):
    assert BANNED_RE.findall(dispatch.render_text(thin)) == []


# --- the dry run -------------------------------------------------------------
def test_dry_run_writes_both_renderings_and_exits_zero(tmp_path):
    out_dir = tmp_path / "dispatch"
    code = dispatch.main(
        ["--data-dir", str(FIXTURE_DIR), "--out-dir", str(out_dir), "--dry-run"]
    )
    assert code == 0
    assert (out_dir / "preview.txt").read_text().startswith("LEDGE")
    assert "<!doctype html>" in (out_dir / "preview.html").read_text().lower()


def test_dry_run_makes_no_network_call(tmp_path, monkeypatch):
    monkeypatch.setenv("RESEND_API_KEY", "re_a_key_that_must_not_be_used")
    monkeypatch.setenv("RESEND_AUDIENCE_ID", "aud_1")
    calls = []
    code = dispatch.main(
        [
            "--data-dir", str(FIXTURE_DIR),
            "--out-dir", str(tmp_path / "dispatch"),
            "--dry-run",
        ],
        transport=lambda *a, **k: calls.append(a) or (200, {}),
    )
    assert code == 0
    assert calls == []


# --- delivery ----------------------------------------------------------------
def test_broadcast_body_is_the_shape_resend_documents(composed):
    body = dispatch.broadcast_body(composed, "aud_1", "LEDGE <dispatch@ledge.tools>")
    assert set(body) == {"segment_id", "from", "subject", "html", "text"}
    assert body["segment_id"] == "aud_1"
    assert body["from"] == "LEDGE <dispatch@ledge.tools>"
    assert body["subject"] == composed["subject"]
    assert body["text"] == dispatch.render_text(composed)
    assert body["html"] == dispatch.render_html(composed)


def test_send_creates_then_sends_the_broadcast(composed):
    calls = []

    def transport(url, payload, api_key, method="POST"):
        calls.append((url, payload, api_key))
        if url.endswith("/broadcasts"):
            return 201, {"object": "broadcast", "id": "bc_1"}
        return 200, {"id": "bc_1"}

    result = dispatch.send(
        composed,
        api_key="re_key",
        audience_id="aud_1",
        sender="LEDGE <dispatch@ledge.tools>",
        transport=transport,
    )
    assert result == {"id": "bc_1"}
    assert [c[0] for c in calls] == [
        "https://api.resend.com/broadcasts",
        "https://api.resend.com/broadcasts/bc_1/send",
    ]
    assert calls[0][2] == "re_key"
    assert calls[0][1]["segment_id"] == "aud_1"
    assert calls[1][1] == {}


def test_send_raises_on_a_resend_error_shape(composed):
    def transport(url, payload, api_key, method="POST"):
        return 422, {"message": "Missing `segment_id` field.", "code": "missing_required_field"}

    with pytest.raises(dispatch.DispatchError) as exc:
        dispatch.send(
            composed,
            api_key="re_key",
            audience_id="",
            sender="LEDGE <dispatch@ledge.tools>",
            transport=transport,
        )
    assert "missing_required_field" in str(exc.value)


def test_main_sends_nothing_without_the_key(tmp_path, monkeypatch):
    monkeypatch.delenv("RESEND_API_KEY", raising=False)
    monkeypatch.setenv("RESEND_AUDIENCE_ID", "aud_1")
    calls = []
    code = dispatch.main(
        ["--data-dir", str(FIXTURE_DIR), "--out-dir", str(tmp_path / "dispatch")],
        transport=lambda *a, **k: calls.append(a) or (200, {}),
    )
    assert code == 1
    assert calls == []
    # the preview is still written, so a run without secrets is still useful
    assert (tmp_path / "dispatch" / "preview.txt").exists()


def test_main_sends_nothing_without_the_audience(tmp_path, monkeypatch):
    monkeypatch.setenv("RESEND_API_KEY", "re_key")
    monkeypatch.delenv("RESEND_AUDIENCE_ID", raising=False)
    calls = []
    code = dispatch.main(
        ["--data-dir", str(FIXTURE_DIR), "--out-dir", str(tmp_path / "dispatch")],
        transport=lambda *a, **k: calls.append(a) or (200, {}),
    )
    assert code == 1
    assert calls == []


def test_main_sends_when_both_secrets_exist(tmp_path, monkeypatch):
    monkeypatch.setenv("RESEND_API_KEY", "re_key")
    monkeypatch.setenv("RESEND_AUDIENCE_ID", "aud_1")
    calls = []

    def transport(url, payload, api_key, method="POST"):
        calls.append(url)
        return (201, {"id": "bc_1"}) if url.endswith("/broadcasts") else (200, {"id": "bc_1"})

    code = dispatch.main(
        ["--data-dir", str(FIXTURE_DIR), "--out-dir", str(tmp_path / "dispatch")],
        transport=transport,
    )
    assert code == 0
    assert len(calls) == 2


# --- the fixture itself ------------------------------------------------------
def test_the_fixture_number_file_is_what_recompute_derives():
    """The frozen number.json must be the pipeline's own output for the
    frozen partitions, or the fixture holds a figure the pipeline would
    never produce."""
    from pipeline.canonical import canonical_dumps
    from pipeline.recompute import recompute

    committed = (FIXTURE_DIR / "number.json").read_text()
    assert committed == canonical_dumps(recompute(FIXTURE_DIR))


def test_the_fixture_number_file_parses_as_schema_v2():
    number = json.loads((FIXTURE_DIR / "number.json").read_text())
    assert number["schemaVersion"] == 2
    assert set(number) >= {"h24", "allTime", "crawledAt", "firstIndexedAt"}
    assert "d7" not in number, "d7 stays internal to dispatch.py; see its docstring"
