"use client";

/* /graduated: every graduation, ranked by how long it took to graduate.

   The build-time row list (public/graduated.json, generated by
   scripts/generate-graduated.mjs) now holds 2,500+ rows and rising by ~250 a
   day, and shipping all of it into every page load put 1.3 MB of HTML in
   front of a reader who only ever reads the first screen of it. Only the
   FIRST PAGE — the first 50 rows, fastest-first, the same default order the
   generator already writes the file in — is rendered at build time and
   passed in as `initialRows`. Any interaction that needs more than that
   (a different sort, a filter, or a page past the first) fetches the same
   public/graduated.json the rest of the site already serves and switches to
   it, once, then holds it in state -- no second fetch on the next filter
   change. Nothing here is estimated while the fetch is in flight: the reader
   sees a wait, not a wrong or a partial answer standing in as a whole one.

   Every duration is a Class B fact: one token's own graduation minus its own
   launch. This component sorts and filters the rows it is given -- it never
   computes a share, a rate, or a percentage, and it carries no verdict
   vocabulary. CONSTRAINTS 1: a ranking is permitted only when the ranked
   quantity is shown, so the duration column is printed on every row
   regardless of which column the table is currently sorted by, and a filter
   is named after the column it filters rather than after a verdict. */

import { useEffect, useMemo, useRef, useState, type MouseEvent, type ReactElement } from "react";
import type { GraduatedFile, GraduatedRow } from "../lib/graduated";
import { graduatedFileSchema } from "../lib/graduated-schema";
import { FilterDate, FilterNumber, FilterSelect } from "./FilterField";
import { Pager } from "./Pager";
import { PAIR_BUCKETS, TAX_BUCKETS, taxBucketOf } from "../lib/board-buckets";
import { clampPage, paginate, totalPagesFor } from "../lib/paginate";
import { mergeQuery, readQuery, readQueryInt } from "../lib/query-state";
import { formatCount, formatDuration, formatUtcLong, pairLabel, taxLabel } from "../lib/format";

export type GraduatedSortKey = "duration" | "durationDesc" | "graduatedAt" | "pair" | "tax";

export const GRADUATED_SORT_KEYS: GraduatedSortKey[] = [
  "duration",
  "durationDesc",
  "graduatedAt",
  "pair",
  "tax",
];

const SORT_LABEL: Record<GraduatedSortKey, string> = {
  duration: "Fastest first",
  durationDesc: "Slowest first",
  graduatedAt: "Most recently graduated",
  pair: "Pair token",
  tax: "Creator tax",
};

const DEFAULT_SORT: GraduatedSortKey = "duration";

/** The JSON file every "?" of the record lives in -- already generated at
    build time and publicly served, so no API dependency is added by fetching
    it a second time on demand. */
const GRADUATED_JSON_URL = "/graduated.json";

interface Filters {
  pair: string; // "" = all, "not-read", or a lib/board-buckets PAIR_BUCKETS value
  tax: string; // "" = all, "not-read", or a lib/board-buckets TAX_BUCKETS value
  ttgMin: string; // seconds, "" = no lower bound
  ttgMax: string; // seconds, "" = no upper bound
  fromDate: string; // yyyy-mm-dd, "" = no lower bound
  toDate: string; // yyyy-mm-dd, "" = no upper bound
}

const DEFAULT_FILTERS: Filters = {
  pair: "",
  tax: "",
  ttgMin: "",
  ttgMax: "",
  fromDate: "",
  toDate: "",
};

function hasActiveFilters(f: Filters): boolean {
  return f.pair !== "" || f.tax !== "" || f.ttgMin !== "" || f.ttgMax !== "" || f.fromDate !== "" || f.toDate !== "";
}

function applyFilters(rows: readonly GraduatedRow[], f: Filters): GraduatedRow[] {
  const ttgMin = f.ttgMin === "" ? null : Number(f.ttgMin);
  const ttgMax = f.ttgMax === "" ? null : Number(f.ttgMax);
  const fromMs = f.fromDate === "" ? null : Date.parse(`${f.fromDate}T00:00:00.000Z`);
  const toMs = f.toDate === "" ? null : Date.parse(`${f.toDate}T23:59:59.999Z`);

  return rows.filter((row) => {
    if (f.pair === "not-read") {
      if (row.pairClass !== null) return false;
    } else if (f.pair !== "" && row.pairClass !== f.pair) {
      return false;
    }
    if (f.tax === "not-read") {
      if (row.creatorTaxBps !== null) return false;
    } else if (f.tax !== "" && taxBucketOf(row.creatorTaxBps) !== f.tax) {
      return false;
    }
    if (ttgMin !== null && Number.isFinite(ttgMin) && row.durationSeconds < ttgMin) return false;
    if (ttgMax !== null && Number.isFinite(ttgMax) && row.durationSeconds > ttgMax) return false;
    if (fromMs !== null && !Number.isNaN(fromMs) && Date.parse(row.graduatedAt) < fromMs) return false;
    if (toMs !== null && !Number.isNaN(toMs) && Date.parse(row.graduatedAt) > toMs) return false;
    return true;
  });
}

function compareRows(a: GraduatedRow, b: GraduatedRow, sort: GraduatedSortKey): number {
  switch (sort) {
    case "duration":
      return a.durationSeconds - b.durationSeconds;
    case "durationDesc":
      return b.durationSeconds - a.durationSeconds;
    case "graduatedAt":
      return Date.parse(b.graduatedAt) - Date.parse(a.graduatedAt);
    case "pair":
      return (
        (a.pairClass ?? "").localeCompare(b.pairClass ?? "") || a.durationSeconds - b.durationSeconds
      );
    case "tax":
      return (
        (a.creatorTaxBps ?? -1) - (b.creatorTaxBps ?? -1) || a.durationSeconds - b.durationSeconds
      );
    default:
      return 0;
  }
}

/* The tax as the reader's own unit. Every other page on this site says "1%"
   and "2-3%", and a column that says "100 bps" beside them is the same fact
   in a second dialect. Basis points are exact, so the conversion is a unit
   change and not a rounding: a tax is set in whole basis points and 100 of
   them is one percent. A value that is not a whole number of tenths keeps its
   basis points rather than being rounded into a tidier lie. */
function taxCell(bps: number | null): string {
  if (bps === null) return "not read";
  const percent = bps / 100;
  return Number.isInteger(percent * 10) ? `${percent}%` : `${bps} bps`;
}

/* The address, shortened the way worker/src/text.ts shortens it, so the same
   token reads the same on its own page and in this list. The full address is
   the link target and the title, so nothing is lost -- it just stops taking
   half the table's width and pushing the columns a reader came for off the
   right-hand edge. */
function shortAddress(address: string): string {
  return `${address.slice(0, 10)}…${address.slice(-6)}`;
}

function pairCell(pairClass: string | null): string {
  return pairClass === null ? "not read" : pairLabel(pairClass);
}

function stateFromLocation(): { sort: GraduatedSortKey; page: number; filters: Filters } {
  const sortParam = readQuery("sort");
  const sort = (GRADUATED_SORT_KEYS as readonly string[]).includes(sortParam ?? "")
    ? (sortParam as GraduatedSortKey)
    : DEFAULT_SORT;
  return {
    sort,
    page: readQueryInt("page") ?? 1,
    filters: {
      pair: readQuery("pair") ?? "",
      tax: readQuery("tax") ?? "",
      ttgMin: readQuery("ttgMin") ?? "",
      ttgMax: readQuery("ttgMax") ?? "",
      fromDate: readQuery("from") ?? "",
      toDate: readQuery("to") ?? "",
    },
  };
}

export function GraduatedBoard({
  initialRows,
  totalCount,
}: {
  initialRows: GraduatedRow[];
  totalCount: number;
}): ReactElement {
  const [sort, setSort] = useState<GraduatedSortKey>(DEFAULT_SORT);
  const [page, setPage] = useState(1);
  const [filters, setFilters] = useState<Filters>(DEFAULT_FILTERS);
  const [fullRows, setFullRows] = useState<GraduatedRow[] | null>(null);
  const [loadState, setLoadState] = useState<"idle" | "loading" | "error">("idle");
  const fetchStarted = useRef(false);

  /* True only when the build-time page does not already hold every row --
     in production, initialRows is 50 of 2,500+; in a test fixture that hands
     the whole set in as initialRows, this is false and nothing ever fetches. */
  const needsFetch = initialRows.length < totalCount;

  async function loadFull(): Promise<void> {
    if (fetchStarted.current) return;
    fetchStarted.current = true;
    setLoadState("loading");
    try {
      const response = await fetch(GRADUATED_JSON_URL);
      if (!response.ok) throw new Error(`graduated.json responded ${response.status}`);
      const json: unknown = await response.json();
      const parsed = graduatedFileSchema.safeParse(json);
      if (!parsed.success) throw new Error("graduated.json did not match the published schema");
      setFullRows((parsed.data as GraduatedFile).rows);
      setLoadState("idle");
    } catch {
      fetchStarted.current = false;
      setLoadState("error");
    }
  }

  useEffect(() => {
    const next = stateFromLocation();
    setSort(next.sort);
    setPage(next.page);
    setFilters(next.filters);
    if (needsFetch && (next.sort !== DEFAULT_SORT || next.page !== 1 || hasActiveFilters(next.filters))) {
      void loadFull();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const sourceRows = fullRows ?? initialRows;
  const filtered = hasActiveFilters(filters);
  const filteredRows = useMemo(() => applyFilters(sourceRows, filters), [sourceRows, filters]);
  const sortedRows = useMemo(
    () => [...filteredRows].sort((a, b) => compareRows(a, b, sort)),
    [filteredRows, sort],
  );
  /* Unfiltered, the true page count is known from totalCount the moment the
     page loads -- sortedRows can be as few as the first 50 rows before the
     full record has been fetched, and computing the page count from that
     partial set would undercount, hiding pages that exist. Filtered, the
     page count comes from the filtered rows themselves: filtering only ever
     runs once the full record has loaded (needsFetch / waitingForFullData
     below), so it is never partial. */
  const pages = filtered ? totalPagesFor(sortedRows.length) : totalPagesFor(totalCount);
  const clampedPage = clampPage(page, pages);
  const pageRows = useMemo(() => paginate(sortedRows, clampedPage), [sortedRows, clampedPage]);

  const waitingForFullData = needsFetch && fullRows === null && (sort !== DEFAULT_SORT || page !== 1 || filtered);

  function chooseSort(key: GraduatedSortKey) {
    return (event: MouseEvent<HTMLAnchorElement>) => {
      event.preventDefault();
      setSort(key);
      setPage(1);
      mergeQuery({ sort: key === DEFAULT_SORT ? null : key, page: null });
      if (needsFetch) void loadFull();
    };
  }

  function updateFilters(patch: Partial<Filters>) {
    const next = { ...filters, ...patch };
    setFilters(next);
    setPage(1);
    mergeQuery({
      pair: next.pair || null,
      tax: next.tax || null,
      ttgMin: next.ttgMin || null,
      ttgMax: next.ttgMax || null,
      from: next.fromDate || null,
      to: next.toDate || null,
      page: null,
    });
    if (needsFetch) void loadFull();
  }

  function resetFilters() {
    setFilters(DEFAULT_FILTERS);
    setPage(1);
    mergeQuery({ pair: null, tax: null, ttgMin: null, ttgMax: null, from: null, to: null, page: null });
  }

  function choosePage(next: number) {
    setPage(next);
    mergeQuery({ page: next === 1 ? null : next });
    if (needsFetch) void loadFull();
  }

  const pairOptions = [
    { value: "", label: "All pair tokens" },
    ...PAIR_BUCKETS.map((p) => ({ value: p, label: pairLabel(p) })),
    { value: "not-read", label: "Not read" },
  ];
  const taxOptions = [
    { value: "", label: "All creator tax bands" },
    ...TAX_BUCKETS.map((t) => ({ value: t, label: taxLabel(t) })),
    { value: "not-read", label: "Not read" },
  ];

  /* Unfiltered, "matched" is always totalCount -- the true population,
     known from the moment the page loads regardless of whether the full row
     set has been fetched yet. Using sortedRows.length here instead would
     print "50 of 50" against the very partial first page this page ships
     with, which is exactly the slice-reads-as-the-whole defect this
     pagination exists to fix. Filtered, the count comes from the filtered
     rows themselves -- filtering only ever runs once the full record has
     loaded (see needsFetch / waitingForFullData above), so it is never
     partial. */
  function countLine(): string {
    const shown = formatCount(pageRows.length);
    if (!filtered) {
      return `${shown} of ${formatCount(totalCount)} graduated tokens shown`;
    }
    const matched = formatCount(sortedRows.length);
    return `${shown} of ${matched} matching tokens shown (${matched} of ${formatCount(totalCount)} total)`;
  }

  return (
    <div className="graduated-board">
      <nav className="sheet-nav live-sort" aria-label="Sort the graduated list">
        {GRADUATED_SORT_KEYS.map((key) =>
          key === sort ? (
            <span key={key} aria-current="true" className="live-sort-current">
              {SORT_LABEL[key]}
            </span>
          ) : (
            <a key={key} href={`?sort=${key}`} onClick={chooseSort(key)}>
              {SORT_LABEL[key]}
            </a>
          ),
        )}
      </nav>

      <div className="board-filters" role="group" aria-label="Filter the graduated list">
        <FilterSelect
          label="Pair token"
          value={filters.pair}
          onChange={(value) => updateFilters({ pair: value })}
          options={pairOptions}
        />
        <FilterSelect
          label="Creator tax"
          value={filters.tax}
          onChange={(value) => updateFilters({ tax: value })}
          options={taxOptions}
        />
        <FilterNumber
          label="Time to graduate from (s)"
          value={filters.ttgMin}
          onChange={(value) => updateFilters({ ttgMin: value })}
        />
        <FilterNumber
          label="Time to graduate to (s)"
          value={filters.ttgMax}
          onChange={(value) => updateFilters({ ttgMax: value })}
        />
        <FilterDate
          label="Graduated from"
          value={filters.fromDate}
          onChange={(value) => updateFilters({ fromDate: value })}
        />
        <FilterDate
          label="Graduated to"
          value={filters.toDate}
          onChange={(value) => updateFilters({ toDate: value })}
        />
        {filtered ? (
          <a
            className="board-filters-reset"
            href="?"
            onClick={(event) => {
              event.preventDefault();
              resetFilters();
            }}
          >
            Reset filters
          </a>
        ) : null}
      </div>

      {waitingForFullData ? (
        loadState === "error" ? (
          <p className="lookup-line-plain">
            The rest of the list did not load.{" "}
            <a
              href="#"
              onClick={(event) => {
                event.preventDefault();
                fetchStarted.current = false;
                void loadFull();
              }}
            >
              Try again
            </a>
            .
          </p>
        ) : (
          <div className="hairline-pulse" />
        )
      ) : (
        <>
          <p className="note note--fine">
            {countLine()} · page {clampedPage} of {pages} · sorted by {SORT_LABEL[sort]}
          </p>

          <div
            className="scroller"
            tabIndex={0}
            role="group"
            aria-label="Every graduation, ranked by time to graduate"
          >
            <table>
              <caption>
                One row per graduated token, ranked only by a column printed on the row itself. Time
                to graduate is that token&rsquo;s own graduation minus its own launch.
              </caption>
              <thead>
                <tr>
                  <th scope="col">Token</th>
                  <th scope="col">Time to graduate</th>
                  <th scope="col">Pair</th>
                  <th scope="col">Creator tax</th>
                  <th scope="col">Graduated</th>
                </tr>
              </thead>
              <tbody>
                {pageRows.map((row) => (
                  <tr key={row.token}>
                    <th scope="row" className="mono">
                      <a href={`/t/${row.token}`} title={row.token}>
                        {shortAddress(row.token)}
                      </a>
                    </th>
                    <td className="fig n mono">{formatDuration(row.durationSeconds)}</td>
                    <td className="fig n">{pairCell(row.pairClass)}</td>
                    <td className="fig n">{taxCell(row.creatorTaxBps)}</td>
                    <td className="thin">{formatUtcLong(row.graduatedAt)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <Pager page={clampedPage} totalPages={pages} onChange={choosePage} label="Page through the graduated list" />

          {sortedRows.length === 0 ? (
            <p className="note note--fine">
              {filtered
                ? "No graduation on record matches these filters."
                : "No graduation joins to a launch on record yet."}
            </p>
          ) : null}
        </>
      )}
    </div>
  );
}
