"use client";

/* /graduated: what a graduation actually looks like, and what just
   graduated. The distribution is the product -- the shape and the ladder
   lead, unchanged in substance from the first build -- and the rows beneath
   them are the evidence, defaulting to most-recently-graduated because a
   visitor here wants to know what just happened, with fastest-first kept one
   click away (REVAMP.md 2026-09-12, "the amendment", boards rebuild).

   Reuses /live's own vocabulary -- `.card`, `.card-header`, `.board-controls`,
   `.board-filter-disclosure`, `.board-what-counts`, `.state-tag`, `.live-card`
   -- rather than inventing a second visual language for a page that is
   structurally the same kind of board: one row per token, sortable and
   filterable by columns every row already shows (CONSTRAINTS 1), no score,
   no grade, no verdict. The column count and the card's own lead figure
   differ from /live's, so the table/card responsive toggle gets its own
   class names (`.graduated-table-wrap` / `.graduated-cards`) rather than
   inheriting /live's fixed eight-column widths.

   The build-time row list (public/graduated.json, generated by
   scripts/generate-graduated.mjs) holds 2,500+ rows and rising, so only the
   FIRST PAGE -- the first 50 rows, in whichever order the page's own default
   sort wants -- ships in the HTML, passed in as `initialRows`. Any other
   sort, filter or page fetches the same public/graduated.json the rest of
   the site already serves, once, then holds it in state.

   Every duration is a Class B fact: one token's own graduation minus its own
   launch. This component sorts and filters the rows it is given -- it never
   computes a share, a rate, or a percentage of its own; the ladder above it
   is the population figure, read verbatim from data/number.json and gated at
   n = 30, and this component never recomputes it. */

import {
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ReactElement,
} from "react";
import type { GraduatedFile, GraduatedRow } from "../lib/graduated";
import { graduatedFileSchema } from "../lib/graduated-schema";
import { FilterDate, FilterNumber, FilterSelect } from "./FilterField";
import { Pager } from "./Pager";
import { Shape } from "./Shape";
import { TokenPanel } from "./TokenPanel";
import { useFreshness } from "./useFreshness";
import { useTokenPanel } from "../lib/use-token-panel";
import { allTime, numberFile } from "../lib/number";
import { PAIR_BUCKETS, TAX_BUCKETS, taxBucketOf } from "../lib/board-buckets";
import { clampPage, paginate, totalPagesFor } from "../lib/paginate";
import { mergeQuery, readQuery, readQueryInt } from "../lib/query-state";
import {
  formatAge,
  formatCount,
  formatDuration,
  formatDurationLong,
  formatStamp,
  formatUtcLong,
  pairLabel,
  rateText,
  taxLabel,
  taxPercent,
} from "../lib/format";

const MIN_N = 30;

export type GraduatedSortKey = "duration" | "durationDesc" | "graduatedAt" | "pair" | "tax";

export const GRADUATED_SORT_KEYS: GraduatedSortKey[] = [
  "duration",
  "durationDesc",
  "graduatedAt",
  "pair",
  "tax",
];

const SORT_LABEL: Record<GraduatedSortKey, string> = {
  duration: "Fastest first",
  durationDesc: "Slowest first",
  graduatedAt: "Most recently graduated",
  pair: "Pair token",
  tax: "Creator tax",
};

/* A visitor lands here to see what just happened, not to find the fastest
   graduation on record -- so the default ranks by recency. Fastest-first
   stays one click away in the same select. */
const DEFAULT_SORT: GraduatedSortKey = "graduatedAt";

/** The JSON file every row of the record lives in -- already generated at
    build time and publicly served, so no API dependency is added by fetching
    it a second time on demand. */
const GRADUATED_JSON_URL = "/graduated.json";

/* "Graduated in" -- the one new filter the amendment asks for, on the
   printed time-to-graduate column (CONSTRAINTS 1 permits filtering by a
   shown quantity). Labelled by the durations only: never "instant", never
   "organic", never "bot" -- those are verdicts about why a token graduated
   that fast, not facts about how fast it graduated. */
type GraduatedInKey = "" | "u10" | "mid" | "over";

const GRADUATED_IN_OPTIONS: { value: GraduatedInKey; label: string }[] = [
  { value: "", label: "All" },
  { value: "u10", label: "Under 10 s" },
  { value: "mid", label: "10 s – 5 min" },
  { value: "over", label: "Over 5 min" },
];

function matchesGraduatedIn(durationSeconds: number, key: GraduatedInKey): boolean {
  switch (key) {
    case "u10":
      return durationSeconds < 10;
    case "mid":
      return durationSeconds >= 10 && durationSeconds < 300;
    case "over":
      return durationSeconds >= 300;
    default:
      return true;
  }
}

interface Filters {
  pair: string; // "" = all, "not-read", or a lib/board-buckets PAIR_BUCKETS value
  tax: string; // "" = all, "not-read", or a lib/board-buckets TAX_BUCKETS value
  ttgMin: string; // seconds, "" = no lower bound
  ttgMax: string; // seconds, "" = no upper bound
  fromDate: string; // yyyy-mm-dd, "" = no lower bound
  toDate: string; // yyyy-mm-dd, "" = no upper bound
  graduatedIn: GraduatedInKey;
}

const DEFAULT_FILTERS: Filters = {
  pair: "",
  tax: "",
  ttgMin: "",
  ttgMax: "",
  fromDate: "",
  toDate: "",
  graduatedIn: "",
};

function hasActiveFilters(f: Filters): boolean {
  return (
    f.pair !== "" ||
    f.tax !== "" ||
    f.ttgMin !== "" ||
    f.ttgMax !== "" ||
    f.fromDate !== "" ||
    f.toDate !== "" ||
    f.graduatedIn !== ""
  );
}

function applyFilters(rows: readonly GraduatedRow[], f: Filters): GraduatedRow[] {
  const ttgMin = f.ttgMin === "" ? null : Number(f.ttgMin);
  const ttgMax = f.ttgMax === "" ? null : Number(f.ttgMax);
  const fromMs = f.fromDate === "" ? null : Date.parse(`${f.fromDate}T00:00:00.000Z`);
  const toMs = f.toDate === "" ? null : Date.parse(`${f.toDate}T23:59:59.999Z`);

  return rows.filter((row) => {
    if (f.pair === "not-read") {
      if (row.pairClass !== null) return false;
    } else if (f.pair !== "" && row.pairClass !== f.pair) {
      return false;
    }
    if (f.tax === "not-read") {
      if (row.creatorTaxBps !== null) return false;
    } else if (f.tax !== "" && taxBucketOf(row.creatorTaxBps) !== f.tax) {
      return false;
    }
    if (ttgMin !== null && Number.isFinite(ttgMin) && row.durationSeconds < ttgMin) return false;
    if (ttgMax !== null && Number.isFinite(ttgMax) && row.durationSeconds > ttgMax) return false;
    if (fromMs !== null && !Number.isNaN(fromMs) && Date.parse(row.graduatedAt) < fromMs) return false;
    if (toMs !== null && !Number.isNaN(toMs) && Date.parse(row.graduatedAt) > toMs) return false;
    if (!matchesGraduatedIn(row.durationSeconds, f.graduatedIn)) return false;
    return true;
  });
}

function compareRows(a: GraduatedRow, b: GraduatedRow, sort: GraduatedSortKey): number {
  switch (sort) {
    case "duration":
      return a.durationSeconds - b.durationSeconds;
    case "durationDesc":
      return b.durationSeconds - a.durationSeconds;
    case "graduatedAt":
      return Date.parse(b.graduatedAt) - Date.parse(a.graduatedAt);
    case "pair":
      return (
        (a.pairClass ?? "").localeCompare(b.pairClass ?? "") || a.durationSeconds - b.durationSeconds
      );
    case "tax":
      return (
        (a.creatorTaxBps ?? -1) - (b.creatorTaxBps ?? -1) || a.durationSeconds - b.durationSeconds
      );
    default:
      return 0;
  }
}

/* The tax as the reader's own unit. Every other page on this site says "1%"
   and "2-3%", and a column that says "100 bps" beside them is the same fact
   in a second dialect. */
function taxCell(bps: number | null): string {
  return taxPercent(bps);
}

/* The address, shortened the way worker/src/text.ts and Live.tsx shorten it,
   so the same token reads the same everywhere. The full address is the link
   target and the title, so nothing is lost. */
function shortAddress(address: string): string {
  return `${address.slice(0, 10)}…${address.slice(-6)}`;
}

function pairCell(pairClass: string | null): string {
  return pairClass === null ? "not read" : pairLabel(pairClass);
}

/** The age since a graduation, in words -- "3 h ago" -- computed on the
    client only, the same way Age.tsx keeps a static export from claiming a
    freshness it cannot know before the browser's own clock has run. Before
    the first tick, and whenever the timestamp cannot be read, the absolute
    UTC stamp is printed instead. */
function GraduatedAt({ iso }: { iso: string }): ReactElement {
  const unreadable = Number.isNaN(Date.parse(iso));
  const [ageSeconds, setAgeSeconds] = useState<number | null>(null);

  useEffect(() => {
    const t = Date.parse(iso);
    if (Number.isNaN(t)) return;
    const tick = () => setAgeSeconds(Math.max(0, Math.round((Date.now() - t) / 1000)));
    tick();
    const id = window.setInterval(tick, 30_000);
    return () => window.clearInterval(id);
  }, [iso]);

  if (unreadable) return <>an unreadable time</>;
  if (ageSeconds === null) return <>{formatUtcLong(iso)}</>;
  return <>{formatAge(ageSeconds)} ago</>;
}

function stateFromLocation(): { sort: GraduatedSortKey; page: number; filters: Filters } {
  const sortParam = readQuery("sort");
  const sort = (GRADUATED_SORT_KEYS as readonly string[]).includes(sortParam ?? "")
    ? (sortParam as GraduatedSortKey)
    : DEFAULT_SORT;
  const gradInParam = readQuery("gradIn");
  const graduatedIn = (["u10", "mid", "over"] as readonly string[]).includes(gradInParam ?? "")
    ? (gradInParam as GraduatedInKey)
    : "";
  return {
    sort,
    page: readQueryInt("page") ?? 1,
    filters: {
      pair: readQuery("pair") ?? "",
      tax: readQuery("tax") ?? "",
      ttgMin: readQuery("ttgMin") ?? "",
      ttgMax: readQuery("ttgMax") ?? "",
      fromDate: readQuery("from") ?? "",
      toDate: readQuery("to") ?? "",
      graduatedIn,
    },
  };
}

/* The ladder's own context table: cumulative shares of ALL-TIME graduations
   completing within each mark, read verbatim from data/number.json's
   allTime.ttg.ladder. These are Class A shares, gated at n = 30, and this
   page never recomputes them. Three columns -- within, graduations, share --
   fit 390px with the share column intact; the sample size is stated once, in
   the caption, rather than repeated in the "Share" head. */
function LadderContext(): ReactElement {
  const { ttg } = allTime;

  if (ttg.insufficient || ttg.n < MIN_N) {
    return (
      <p className="note">
        {`not enough data (n=${formatCount(ttg.n)}) to place a graduation against the population.`}
      </p>
    );
  }

  return (
    <>
      <div
        className="scroller"
        tabIndex={0}
        role="group"
        aria-label="Cumulative share of all-time graduations by time to graduate"
      >
        <table>
          <caption>Of {formatCount(ttg.n)} graduations, how many had finished by each mark.</caption>
          <thead>
            <tr>
              <th scope="col">Within</th>
              <th scope="col">Graduations</th>
              <th scope="col">Share</th>
            </tr>
          </thead>
          <tbody>
            {ttg.ladder.map((rung) => (
              <tr key={rung.atSeconds}>
                <th scope="row">{formatDurationLong(rung.atSeconds)}</th>
                <td className="fig n">{formatCount(rung.cumulative)}</td>
                <td className="fig">
                  {rateText({ rate: rung.cumulativeShare, n: ttg.n, insufficient: ttg.insufficient })}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="note note--fine">
        Median time to graduate {ttg.p50 === null ? "not enough data" : formatDurationLong(ttg.p50)}
        ; slowest observed {ttg.max === null ? "not enough data" : formatDurationLong(ttg.max)}. n
        {" = "}
        {formatCount(ttg.n)} matched graduations, {formatStamp(numberFile.crawledAt)}.
      </p>
    </>
  );
}

/* One card per token below the table's own breakpoint (the same 64rem /live
   picks up its desktop layout at). The lead figure is the duration -- large,
   mono -- because the job of this board is "what did this graduation look
   like", and the duration is the answer; the door, the pair, the tax and the
   graduated-at age follow, quieter. */
function GraduatedCard({
  row,
  onOpen,
}: {
  row: GraduatedRow;
  onOpen: (address: string, trigger: HTMLElement | null) => void;
}): ReactElement {
  return (
    <li
      className="live-card row-clickable"
      tabIndex={0}
      onClick={(event) => {
        if ((event.target as HTMLElement).closest("a")) return;
        onOpen(row.token, event.currentTarget);
      }}
      onKeyDown={(event) => {
        if (event.key !== "Enter" && event.key !== " ") return;
        if ((event.target as HTMLElement).closest("a")) return;
        event.preventDefault();
        onOpen(row.token, event.currentTarget);
      }}
    >
      <a className="live-card-token mono" href={`/t/${row.token}`} title={row.token}>
        {shortAddress(row.token)}
      </a>
      <p className="graduated-card-duration mono">graduated in {formatDuration(row.durationSeconds)}</p>
      <p className="note note--fine live-card-analyst">
        {pairCell(row.pairClass)} · {taxCell(row.creatorTaxBps)} ·{" "}
        <GraduatedAt iso={row.graduatedAt} />
      </p>
    </li>
  );
}

export interface GraduatedBoardProps {
  initialRows: GraduatedRow[];
  totalCount: number;
  generatedAt: string;
  staleAfterSeconds: number;
  totalGraduationRows: number;
  excludedNoLaunch: number;
  excludedUnmatched: number;
}

export function GraduatedBoard({
  initialRows,
  totalCount,
  generatedAt,
  staleAfterSeconds,
  totalGraduationRows,
  excludedNoLaunch,
  excludedUnmatched,
}: GraduatedBoardProps): ReactElement {
  const [sort, setSort] = useState<GraduatedSortKey>(DEFAULT_SORT);
  const [page, setPage] = useState(1);
  const [filters, setFilters] = useState<Filters>(DEFAULT_FILTERS);
  const panel = useTokenPanel();
  const [fullRows, setFullRows] = useState<GraduatedRow[] | null>(null);
  const [loadState, setLoadState] = useState<"idle" | "loading" | "error">("idle");
  const fetchStarted = useRef(false);
  const sortId = useId();
  const filterDetailsRef = useRef<HTMLDetailsElement | null>(null);
  const { ageSeconds, stale, unreadable } = useFreshness(generatedAt, staleAfterSeconds);

  /* True only when the build-time page does not already hold every row --
     in production, initialRows is 50 of 2,500+; in a test fixture that hands
     the whole set in as initialRows, this is false and nothing ever fetches. */
  const needsFetch = initialRows.length < totalCount;

  async function loadFull(): Promise<void> {
    if (fetchStarted.current) return;
    fetchStarted.current = true;
    setLoadState("loading");
    try {
      const response = await fetch(GRADUATED_JSON_URL);
      if (!response.ok) throw new Error(`graduated.json responded ${response.status}`);
      const json: unknown = await response.json();
      const parsed = graduatedFileSchema.safeParse(json);
      if (!parsed.success) throw new Error("graduated.json did not match the published schema");
      setFullRows((parsed.data as GraduatedFile).rows);
      setLoadState("idle");
    } catch {
      fetchStarted.current = false;
      setLoadState("error");
    }
  }

  useEffect(() => {
    const next = stateFromLocation();
    setSort(next.sort);
    setPage(next.page);
    setFilters(next.filters);
    if (needsFetch && (next.sort !== DEFAULT_SORT || next.page !== 1 || hasActiveFilters(next.filters))) {
      void loadFull();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /* The filter disclosure opens by default at >=64rem, closed below -- read
     once on mount the same way Live.tsx's own filter disclosure is, so a
     phone's first screen is the board itself. */
  useEffect(() => {
    const details = filterDetailsRef.current;
    if (!details || typeof window === "undefined" || typeof window.matchMedia !== "function") return;
    details.open = window.matchMedia("(min-width: 64rem)").matches;
  }, []);

  const sourceRows = fullRows ?? initialRows;
  const filtered = hasActiveFilters(filters);
  const filteredRows = useMemo(() => applyFilters(sourceRows, filters), [sourceRows, filters]);
  const sortedRows = useMemo(
    () => [...filteredRows].sort((a, b) => compareRows(a, b, sort)),
    [filteredRows, sort],
  );
  const pages = filtered ? totalPagesFor(sortedRows.length) : totalPagesFor(totalCount);
  const clampedPage = clampPage(page, pages);
  const pageRows = useMemo(() => paginate(sortedRows, clampedPage), [sortedRows, clampedPage]);

  const waitingForFullData = needsFetch && fullRows === null && (sort !== DEFAULT_SORT || page !== 1 || filtered);

  function chooseSort(key: GraduatedSortKey) {
    setSort(key);
    setPage(1);
    mergeQuery({ sort: key === DEFAULT_SORT ? null : key, page: null });
    if (needsFetch) void loadFull();
  }

  function updateFilters(patch: Partial<Filters>) {
    const next = { ...filters, ...patch };
    setFilters(next);
    setPage(1);
    mergeQuery({
      pair: next.pair || null,
      tax: next.tax || null,
      ttgMin: next.ttgMin || null,
      ttgMax: next.ttgMax || null,
      from: next.fromDate || null,
      to: next.toDate || null,
      gradIn: next.graduatedIn || null,
      page: null,
    });
    if (needsFetch) void loadFull();
  }

  function resetFilters() {
    setFilters(DEFAULT_FILTERS);
    setPage(1);
    mergeQuery({ pair: null, tax: null, ttgMin: null, ttgMax: null, from: null, to: null, gradIn: null, page: null });
  }

  function choosePage(next: number) {
    setPage(next);
    mergeQuery({ page: next === 1 ? null : next });
    if (needsFetch) void loadFull();
  }

  const pairOptions = [
    { value: "", label: "All pair tokens" },
    ...PAIR_BUCKETS.map((p) => ({ value: p, label: pairLabel(p) })),
    { value: "not-read", label: "Not read" },
  ];
  const taxOptions = [
    { value: "", label: "All creator tax bands" },
    ...TAX_BUCKETS.map((t) => ({ value: t, label: taxLabel(t) })),
    { value: "not-read", label: "Not read" },
  ];

  function countLine(): string {
    const shown = formatCount(pageRows.length);
    if (!filtered) {
      return `${shown} of ${formatCount(totalCount)} graduated tokens shown`;
    }
    const matched = formatCount(sortedRows.length);
    return `${shown} of ${matched} matching tokens shown (${matched} of ${formatCount(totalCount)} total)`;
  }

  const ageText = unreadable
    ? "list built at an unreadable time"
    : ageSeconds === null
      ? "…"
      : `list built ${formatAge(ageSeconds)} ago`;

  return (
    <div className={`card graduated-board${stale ? " is-stale-card" : ""}`}>
      <div className="card-header">
        <span className={`kicker card-kicker${stale ? " is-stale" : ""}`}>
          GRADUATED · {formatCount(totalCount)} graduation{totalCount === 1 ? "" : "s"} timed
        </span>
        <span className={`note note--fine mono${stale ? " is-stale" : ""}`}>{ageText}</span>
      </div>

      <p className="note note--fine" style={{ marginTop: "0" }}>
        Counted over {formatCount(allTime.ttg.n)} graduations.
      </p>
      <Shape histogram={allTime.ttg.histogram} n={allTime.ttg.n} insufficient={allTime.ttg.insufficient} />

      <LadderContext />

      <div className="board-controls">
        <p className="picker-field live-sort-field">
          <label className="picker-label" htmlFor={sortId}>
            Sort
          </label>
          <span className="picker-line">
            <select
              className="picker-select mono"
              id={sortId}
              value={sort}
              onChange={(event) => chooseSort(event.target.value as GraduatedSortKey)}
            >
              {GRADUATED_SORT_KEYS.map((key) => (
                <option key={key} value={key}>
                  {SORT_LABEL[key]}
                </option>
              ))}
            </select>
            <span className="picker-caret" aria-hidden="true">
              ▾
            </span>
          </span>
        </p>

        <details className="board-filter-disclosure" ref={filterDetailsRef}>
          <summary>{filtered ? "Filter · active" : "Filter"}</summary>
          <div className="board-filters" role="group" aria-label="Filter the graduated list">
            <FilterSelect
              label="Pair token"
              value={filters.pair}
              onChange={(value) => updateFilters({ pair: value })}
              options={pairOptions}
            />
            <FilterSelect
              label="Creator tax"
              value={filters.tax}
              onChange={(value) => updateFilters({ tax: value })}
              options={taxOptions}
            />
            <FilterSelect
              label="Graduated in"
              value={filters.graduatedIn}
              onChange={(value) => updateFilters({ graduatedIn: value as GraduatedInKey })}
              options={GRADUATED_IN_OPTIONS}
            />
            <FilterNumber
              label="Time to graduate from (s)"
              value={filters.ttgMin}
              onChange={(value) => updateFilters({ ttgMin: value })}
            />
            <FilterNumber
              label="Time to graduate to (s)"
              value={filters.ttgMax}
              onChange={(value) => updateFilters({ ttgMax: value })}
            />
            <FilterDate
              label="Graduated from"
              value={filters.fromDate}
              onChange={(value) => updateFilters({ fromDate: value })}
            />
            <FilterDate
              label="Graduated to"
              value={filters.toDate}
              onChange={(value) => updateFilters({ toDate: value })}
            />
            {filtered ? (
              <a
                className="board-filters-reset"
                href="?"
                onClick={(event) => {
                  event.preventDefault();
                  resetFilters();
                }}
              >
                Reset filters
              </a>
            ) : null}
          </div>
        </details>
      </div>

      {waitingForFullData ? (
        loadState === "error" ? (
          <p className="lookup-line-plain">
            The rest of the list did not load.{" "}
            <a
              href="#"
              onClick={(event) => {
                event.preventDefault();
                fetchStarted.current = false;
                void loadFull();
              }}
            >
              Try again
            </a>
            .
          </p>
        ) : (
          <div className="hairline-pulse" />
        )
      ) : (
        <>
          <div
            className="scroller graduated-table-wrap"
            tabIndex={0}
            role="group"
            aria-label="Every graduation, ranked by time to graduate"
          >
            <table>
              <caption>
                Time to graduate is launch to graduation, from the chain.{" "}
                {formatCount(totalGraduationRows - excludedNoLaunch - excludedUnmatched)} graduations
                are timed; {formatCount(excludedNoLaunch)} are not, because their launch is not on
                record
                {excludedUnmatched > 0
                  ? `, and ${formatCount(excludedUnmatched)} more could not be matched to a launch`
                  : ""}
                .
              </caption>
              <thead>
                <tr>
                  <th scope="col">Token</th>
                  <th scope="col">Time to graduate</th>
                  <th scope="col">Pair</th>
                  <th scope="col">Creator tax</th>
                  <th scope="col">Graduated</th>
                </tr>
              </thead>
              <tbody>
                {pageRows.map((row) => (
                  <tr
                    key={row.token}
                    className="row-clickable"
                    tabIndex={0}
                    onClick={(event) => {
                      if ((event.target as HTMLElement).closest("a")) return;
                      panel.open(row.token, event.currentTarget);
                    }}
                    onKeyDown={(event) => {
                      if (event.key !== "Enter" && event.key !== " ") return;
                      if ((event.target as HTMLElement).closest("a")) return;
                      event.preventDefault();
                      panel.open(row.token, event.currentTarget);
                    }}
                  >
                    <th scope="row" className="mono">
                      <a href={`/t/${row.token}`} title={row.token}>
                        {shortAddress(row.token)}
                      </a>
                    </th>
                    <td className="fig n mono">{formatDuration(row.durationSeconds)}</td>
                    <td className="fig n">{pairCell(row.pairClass)}</td>
                    <td className="fig n">{taxCell(row.creatorTaxBps)}</td>
                    <td className="fig n">
                      <GraduatedAt iso={row.graduatedAt} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <ul className="graduated-cards" aria-label="Every graduation, ranked by time to graduate">
            {pageRows.map((row) => (
              <GraduatedCard key={row.token} row={row} onOpen={panel.open} />
            ))}
          </ul>

          <p className="note note--fine">
            {countLine()} · page {clampedPage} of {pages} · sorted by {SORT_LABEL[sort]}
          </p>

          <Pager page={clampedPage} totalPages={pages} onChange={choosePage} label="Page through the graduated list" />

          {sortedRows.length === 0 ? (
            <p className="note note--fine">
              {filtered
                ? "No graduation on record matches these filters."
                : "No graduation joins to a launch on record yet."}
            </p>
          ) : null}

          <details className="board-what-counts">
            <summary>How these are counted</summary>
            <p className="lede">
              Time to graduate is one token&rsquo;s own graduation timestamp minus its own launch
              timestamp -- a fact about that token, not a rate over the population. The ladder above
              is the population figure, computed once by the same pipeline that produces the rest of
              the site and gated at n = 30; this list never recomputes a share or a percentage.
            </p>
            <p className="note">
              No row carries a label beyond its own facts. The duration is printed; nothing here
              says what it means.
            </p>
          </details>
        </>
      )}
      {panel.token ? (
        <TokenPanel token={panel.token} onClose={panel.close} returnFocusTo={panel.returnFocusTo} />
      ) : null}
    </div>
  );
}
